version: 2.1

orbs:
  terraform: circleci/terraform@1.0.2
  gcp-cli: circleci/gcp-cli@1.8.5

jobs:
  apply_gke_cluster:
    executor: terraform/default
    working_directory: ~/terraformTest/gke_cluster
    steps:
      - run: apk add bash curl python3-dev
      - run: curl https://sdk.cloud.google.com > install.sh
      - run: bash install.sh --disable-prompts
      #- run: curl -sSL https://sdk.cloud.google.com | bash
      #- gcp-cli/install
      - gcp-cli/initialize
      - checkout
      - terraform/init
      - terraform/validate
      - terraform/fmt
      - terraform/plan
      #- terraform/apply:
      #    path: gke_cluster
    #working_directory: ~/gke_cluster

workflows:
  single-job-lifecycle:
    jobs:
      - apply_gke_cluster