version: 2.1

orbs:
  terraform: circleci/terraform@1.0.2
  gcp-cli: circleci/gcp-cli@1.8.5

jobs:
  apply_gke_cluster:
    executor: terraform/default
    shell: /bin/bash -eo pipefail
    steps:
      - checkout
      - run:
          shell: /bin/sh -eo pipefail
          command: apk add bash curl python3-dev
      
      - run: curl https://sdk.cloud.google.com > install.sh
      - run: bash install.sh --disable-prompts
      - run: echo $GCLOUD_SERVICE_KEY > creds.json
      #- run: ls -la
      - run: /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=creds.json
      - run: /root/google-cloud-sdk/bin/gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - run: /root/google-cloud-sdk/bin/gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

      - terraform/init:
          path: gke_cluster
      - terraform/validate:
          path: gke_cluster
      - terraform/fmt:
          path: gke_cluster
      - terraform/plan:
          path: gke_cluster
      #- terraform/apply:
      #    path: gke_cluster

workflows:
  single-job-lifecycle:
    jobs:
      - apply_gke_cluster